// Kahoot UZ qahramonlari — har biri o'zbek milliy ranglari va do'ppisi bilan
export const characters = [
  {
    id: 'anora',
    name: 'Anora',
    role: 'Bilimlar malikasi',
    color: '#E24A3B',
    doppiColor: '#12213A',
    accent: '#FFC94D',
    blurb: "Anordek qip-qizil. Har savolga shaxdam va aniq javob beradi.",
  },
  {
    id: 'bobur',
    name: 'Bobur',
    role: 'Sarkarda',
    color: '#1EA5B8',
    doppiColor: '#12213A',
    accent: '#FBF3E4',
    blurb: "Strategiya ustasi. Ball to'plashda unga teng keladigan yo'q.",
  },
  {
    id: 'gulnoza',
    name: 'Gulnoza',
    role: "Suzana chizuvchisi",
    color: '#F5A623',
    doppiColor: '#2B3A8C',
    accent: '#E24A3B',
    blurb: "Naqshdek nafis fikrlaydi. Eng chalkash savollarni yechadi.",
  },
  {
    id: 'sardor',
    name: 'Sardor',
    role: "Jamoa boshlig'i",
    color: '#1B7A4B',
    doppiColor: '#12213A',
    accent: '#FFC94D',
    blurb: "Jamoa o'yinida hamma uni tanlaydi — chunki u doim yordam beradi.",
  },
  {
    id: 'malika',
    name: 'Malika',
    role: 'Tezkor o‘yinchi',
    color: '#6A5CF5',
    doppiColor: '#12213A',
    accent: '#33E0E8',
    blurb: "Har doim birinchi javob beradi — reflekslari chaqmoqdek tez.",
  },
  {
    id: 'jasur',
    name: 'Jasur',
    role: 'Streak ustasi',
    color: '#FF4D5E',
    doppiColor: '#0B1220',
    accent: '#FFC94D',
    blurb: "Ketma-ket to'g'ri javoblar bilan reyting cho'qqisini egallaydi.",
  },
  {
    id: 'nilufar',
    name: 'Nilufar',
    role: "Lug'at ustasi",
    color: '#33E0E8',
    doppiColor: '#2B3A8C',
    accent: '#FF4D5E',
    blurb: "Har bir so'zning tagiga yetadi. Lug'at savollarida unga teng kelmaydi.",
  },
  {
    id: 'davron',
    name: 'Davron',
    role: 'Xotirjam strateg',
    color: '#F5A623',
    doppiColor: '#0B1220',
    accent: '#2FD583',
    blurb: "Shoshilmaydi, lekin hech qachon xato qilmaydi.",
  },
]

export const quizzes = [
  {
    id: 'present-simple',
    title: 'Present Simple asoslari',
    questions: 12,
    level: '5–6-sinf',
    color: '#E24A3B',
    emoji: '📘',
  },
  {
    id: 'vocabulary',
    title: "Kundalik lug'at boyligi",
    questions: 15,
    level: '5–9-sinf',
    color: '#1368CE',
    emoji: '🔤',
  },
  {
    id: 'listening',
    title: 'Tinglab tushunish',
    questions: 10,
    level: '7–9-sinf',
    color: '#2B3A8C',
    emoji: '🎧',
  },
  {
    id: 'reading',
    title: "O'qish va tushunish",
    questions: 14,
    level: '8–11-sinf',
    color: '#1B7A4B',
    emoji: '📖',
  },
]
